In [1]:
# 7.4
import pandas as pd

Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [2]:
# Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию
import numpy as np

com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

P = Price_DF.values
C = Count_DF.values
salon_inc = (P*C)@(com)
print(salon_inc)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [5]:
P

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [6]:
C

array([[10,  5, 12, 15, 10],
       [ 2, 21,  3, 25,  6],
       [12, 12,  0, 30,  4],
       [ 4,  8, 18, 14,  5],
       [ 6, 25, 27, 25, 18],
       [10,  3,  2, 17, 12],
       [22,  1,  4, 25, 20],
       [ 7,  0, 31, 31, 28]])

In [7]:
P*C

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])